;>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
;	1DT301, Computer Technology 1
;	Date: 09-09-2019
;	Authors:
;		Roel de Vries
;		Student name 2
;
;	Lab number 1
;	Title:	How to use the PORTS, digital IO, subroutine call
;
;	Hardware: STK600, CPU ATmega 2560
;
;	Function: Creates a johnson counter, updates every 0.5 seconds
;
;	Input ports: None
;
;	Output ports: PORTB, used for LEDS
;
;	Subroutines: Timer
;	Included files: m2560def.inc
;
;	Other information: None
;
;	Changes in program: 
;		09-09-2019 > file created
;<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
.include "m2560def.inc"

main:
	; Initialize SP, Stack Pointer
	ldi r21, HIGH(RAMEND) ; R20 = high part of RAMEND address
	out SPH,R21 ; SPH = high part of RAMEND address
	ldi R21, low(RAMEND) ; R20 = low part of RAMEND address
	out SPL,R21 ; SPL = low part of RAMEND address

	CBR r16, 0; counter
	SBR r17, 255; light state 
	OUT DDRB, r17
	ldi r16, 8

incloop:
	LSL r17
	OUT PORTB, r17
	call timer
	dec r16
    brne incloop
	ldi r16, 8
	call decloop

decloop:
	LSR r17
	SBR r17, 128
	OUT PORTB, r17
	call timer
	dec r16
    brne decloop
	ldi r16, 8
	call incloop

timer:
; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
	ldi  r18, 5
    ldi  r19, 20
    ldi  r20, 175
L1: dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
    rjmp PC+1
	ret

