;
; lab3.asm
;
; Created: 2019-09-23 13:41:25
; Author : ak223wd
;


.include "m2560def.inc"
;The term VECTOR means nothing more than that each interrupt has its specific address where it jumps to. 
; The term TABLE means it is a list of jump instructions. This is a list of rjmp or jmp instructions, sorted by interrupt priority

.org 0x00 ;This is the location that the program will start executing from
rjmp start 

.org INT0addr
rjmp interrupt

.org 0x72
start:
	; Initialize SP, Stack Pointer
	ldi r16, HIGH(RAMEND) ; R20 = high part of RAMEND address
	out SPH,r16 ; SPH = high part of RAMEND address
	ldi r16, low(RAMEND) ; R20 = low part of RAMEND address
	out SPL,r16 ; SPL = low part of RAMEND address



	;Main program initialization 
	ldi r16, 0xFF ; 
	out DDRB, r16 ; we set the DDRB as output


	ldi r17, 0b00000001 ;we set the corresponding bit number to enable the related interrupt here INT0
	out EIMSK, r17 ; Toggle external interrupt requests


	ldi r17, 0b00000010 ;We define the type of signals that activates the external interrupt , here we set it as falling edge to activate the interrupt
	sts EICRA, r17 ;we configure when to switch the external interrupt 

	sei ;enabling all interrupts

ldi r25, 0b11111111 ;START

ldi r16, 0b11111111
ldi r22, 0b00000000

main_program:
	cp r25, r16
	breq ring_counter		
rjmp main_program
 
ring_counter:
	ldi r18, 0b11111110
	;WE COMPARE
	cp r25, r22 ;0000 0000
	breq johnson_counter

ring_loop:
	out PORTB, r18 ;we put the value of r18 to PORTB which should turn on the light
	call Delay
	com r18
	LSL r18
	com r18

	;Check if everything is off if true then go to ring counter to make infinite loop
	ldi r24,0xFF
	cp r24, r18
	breq ring_counter

	;WE COMPARE
	cp r25, r22 ;0000 0000
	breq johnson_counter


rjmp ring_loop

johnson_counter : 	
	ldi r19, 0b11111110 ;Turn on light at 0
	
	cp r25, r16 ;1111 1111
	breq ring_counter

	ldi r22, 0x00

johnson_loop:
	out PORTB, r19
	LSL r19
	call Delay
	cp r19, r22
	breq johnson

	;WE COMPARE
	cp r25, r16 ;1111 1111
	breq ring_counter

	rjmp johnson_loop


johnson : 
	out PORTB, r22
	ldi r22, 0b11111111
	call Delay
	ldi r19,0b10000000

	more_john : 
		out PORTB, r19
		ASR r19
		call Delay 
		cp r19, r22
		breq johnson_counter

		;WE COMPARE
		cp r25, r16
		breq ring_counter

	rjmp more_john


 interrupt:
	com r25	;we take the completement
reti


Delay :
; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html

	ldi  r21, 5
    ldi  r23, 20
    ldi  r24, 175
L1: dec  r24
    brne L1
    dec  r23
    brne L1
    dec  r21
    brne L1
	ret



	 
